# Generated by Django 5.1.4 on 2024-12-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0003_alter_dogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogpost',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], null=True),
        ),
    ]
