# Generated by Django 5.1.4 on 2024-12-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0004_dogpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogpost',
            name='type',
        ),
        migrations.AlterField(
            model_name='dogpost',
            name='status',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('found', 'Found'), ('adopted', 'Adopted')], null=True),
        ),
    ]
