# Generated by Django 5.1.4 on 2024-12-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='dog_post',
        ),
    ]
