# Generated by Django 5.1.4 on 2025-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0009_alter_doguser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doguser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
