# Generated by Django 5.1.4 on 2025-02-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0012_alter_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_posts', to='dog_api.doguser'),
        ),
    ]
